= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.2.4...v1.2.5++[1.2.5^] (2021-04-30)

=== Bug Fixes

* *gpg:* update Hashicorp GPG key after HCSEC-2021-12
(https://github.com/saltstack-formulas/vault-formula/commit/1b6d000e9ab44aed7442c41f08ba2638bf19f81f[1b6d000^])

=== Continuous Integration

* *kitchen+gitlab:* adjust matrix to add `3003` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/d7ea9ae7f4e082eab964ee98201f1e8be6c7685d[d7ea9ae^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.2.3...v1.2.4++[1.2.4^] (2021-04-17)

=== Code Refactoring

* *cert-gen.sh:* use `sh` not `bash` for portability
(https://github.com/saltstack-formulas/vault-formula/commit/860f1ba897b7cc7697786ad771f581eb4b41357e[860f1ba^])

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/134d6f5c88ca3652dd9719fae57c1b72c248fe48[134d6f5^])
* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/999e3c7456becf3473776baeb9ac5a11e575922a[999e3c7^])
* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/c6bf47b84525ada706d386a72bf29205c4bffc45[c6bf47b^])
* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/f3c10079754aee725a54a15781d1ec5cb450fbf7[f3c1007^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/31a61f88ee27c9703a7d274853d7bee6614aaa7e[31a61f8^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/vault-formula/commit/0a90aa782633570279d391cd2a398868c9f19ca3[0a90aa7^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/6d0cff052848a3c9a1334b65112e27c6caba5b91[6d0cff0^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/7403ecda559f3133f66005dca29ef832b0f44a45[7403ecd^])
* *kitchen:* use `stable` for `amazonlinux-1` bootstrap [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/83930ff0bc62f9cfe5cef161b7c735c02b9e1745[83930ff^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/49e56719cbf8ca03568196f7c95fa434229b1776[49e5671^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/d96b7899688677fbafc98f4fbdf8f987142b8e8c[d96b789^])
* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/98bad0d8eeeae9899bbde3a46062e03cc488a090[98bad0d^])
* *kitchen+travis:* adjust matrix to add `3000.1` & remove `2017.7`
(https://github.com/saltstack-formulas/vault-formula/commit/37ce4f4f5e5247c81630d04bade8f01c4cdd34a5[37ce4f4^])
* *kitchen+travis:* adjust matrix to add `3000.2` & remove `2018.3`
 [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/3ffb96f20aa7b2b15897abc5998996972160eb41[3ffb96f^])
* *kitchen+travis:* adjust matrix to add `3000.3` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/fe39213f1065bd950cd2ea44ee9706840031e915[fe39213^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/43e6673c14c99f4767b0fa80886c82efa8ab8fda[43e6673^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/034157bbea2bd5237ab0fcaab47b380b7fc441fd[034157b^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/d8b64e3f7418d02c97e718506fc06b3e397bb9b3[d8b64e3^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/e42dc17e7af9dfa928b3caf211b222744067a3b7[e42dc17^])
* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/99be48451b6a1093df4e34d0ec4d11e8248fd833[99be484^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/279a5b447bb24af41c7a9964662d94c271273359[279a5b4^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/d494294a98171368cecfc95c5ef29ee4807c454d[d494294^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/vault-formula/commit/b8e3f4faa46e1b7e089cd4f4d7618bd2de855b0b[b8e3f4f^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/f4beb3368dd319474b7ef3b517df23f24f902bc6[f4beb33^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/c4090d695886352314677b5968949a6e9c7fc082[c4090d6^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/1ab38018c69130a62c19006b81a324afdfc1bf67[1ab3801^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/b54b06d8c4c13998107b8eaf5dafb93b3c785d98[b54b06d^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/98e056ada33c8e0c5db4eb0e6a8227f0cfe829dc[98e056a^])

=== Tests

* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/9877500f0a13bbb68d0b7f1e625e9587369e62ef[9877500^])
* *prod_server:* fix regex for Arch and Tumbleweed as well
(https://github.com/saltstack-formulas/vault-formula/commit/9d673fa81d1e25c98ee37e47c9380639b47c75c3[9d673fa^])
* *rubocop:* fix remaining violations
(https://github.com/saltstack-formulas/vault-formula/commit/d289ce9303637efc58f13ce71ec521fcad05231e[d289ce9^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.2.2...v1.2.3++[1.2.3^] (2019-11-07)

=== Bug Fixes

* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/297db702a9956dbfb24c3a9eb484bff151cdb3c2[297db70^])

=== Continuous Integration

* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/bc13a28c4ca3a746dc9b79d87e66bd4cda566164[bc13a28^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/c38389c181dfb663c7783680f5f448676647882c[c38389c^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/8c9631efeaee70843ce1e727b47582292a192f33[8c9631e^])
* *kitchen+travis:* use bootstrapped `amazonlinux-1` images
(https://github.com/saltstack-formulas/vault-formula/commit/a9576e816b292cd47abe4c609b794b16f879cc87[a9576e8^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/562874c1eba10f8cd196ca3fb965cb11a3333950[562874c^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/vault-formula/commit/af7f5037c0b15b481f1cfd3d24e18ab5faed5fb6[af7f503^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/7214aa7361104b183b16fea0b3bea0a1974ba46d[7214aa7^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/e5542dd3c4c1333340fa8f13ad1caf39f5552167[e5542dd^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/vault-formula/commit/8b098a3a2729740c25e9204c150e8679ba8546bd[8b098a3^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.2.1...v1.2.2++[1.2.2^] (2019-10-09)

=== Bug Fixes

* *cert-gen.sh.j2:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/vault-formula/commit/12fd2f9[12fd2f9^])

=== Continuous Integration

* *kitchen:* install required packages to bootstrapped `opensuse`
(https://github.com/saltstack-formulas/vault-formula/commit/5f1c3cd[5f1c3cd^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2`
(https://github.com/saltstack-formulas/vault-formula/commit/c090077[c090077^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/vault-formula/commit/ba82312[ba82312^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.2.0...v1.2.1++[1.2.1^] (2019-10-01)

=== Bug Fixes

* *gemfile:* restrict `inspec` version to `~> 4.16.0`
(https://github.com/saltstack-formulas/vault-formula/commit/c82034a[c82034a^]),
closes
https://github.com//travis-ci.com/saltstack-formulas/vault-formula/jobs/239671364/issues/L2219-L2220[/travis-ci.com/saltstack-formulas/vault-formula/jobs/239671364#L2219-L2220^]
https://github.com//travis-ci.com/saltstack-formulas/vault-formula/jobs/239671365/issues/L1925-L1926[/travis-ci.com/saltstack-formulas/vault-formula/jobs/239671365#L1925-L1926^]
https://github.com//travis-ci.com/saltstack-formulas/vault-formula/jobs/239671366/issues/L1515-L1520[/travis-ci.com/saltstack-formulas/vault-formula/jobs/239671366#L1515-L1520^]
* *inspec:* fix Ruby lint warnings
(https://github.com/saltstack-formulas/vault-formula/commit/9d823ed[9d823ed^])
* *osfamilymap:* add support for `Arch`
(https://github.com/saltstack-formulas/vault-formula/commit/b64a589[b64a589^])

=== Continuous Integration

* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/vault-formula/commit/d2c97f4[d2c97f4^])
* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/vault-formula/commit/79b902e[79b902e^])
* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/vault-formula/commit/346cd1e[346cd1e^])
* *platform:* add `arch-base-latest`
(https://github.com/saltstack-formulas/vault-formula/commit/6dd656f[6dd656f^])
* *travis:* apply suggestions from code review
(https://github.com/saltstack-formulas/vault-formula/commit/800d842[800d842^])
* *travis:* split suites across instances
(https://github.com/saltstack-formulas/vault-formula/commit/bfdba0c[bfdba0c^])
* *travis:* use `kitchen verify` instead of `kitchen test`
(https://github.com/saltstack-formulas/vault-formula/commit/6939af9[6939af9^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/vault-formula/commit/ece89fa[ece89fa^])

=== Tests

* *inspec:* move tests to standard `controls` sub-directory
(https://github.com/saltstack-formulas/vault-formula/commit/bd8649c[bd8649c^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.1.1...v1.2.0++[1.2.0^] (2019-08-17)

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/vault-formula/commit/073f66e[073f66e^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.1.0...v1.1.1++[1.1.1^] (2019-07-13)

=== Code Refactoring

* *kitchen+inspec:* move inline pillars to files
(https://github.com/saltstack-formulas/vault-formula/commit/4dc3025[4dc3025^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.6...v1.1.0++[1.1.0^] (2019-07-10)

=== Bug Fixes

* *package:* explicitly require package providing setcap
(https://github.com/saltstack-formulas/vault-formula/commit/d476700[d476700^])
* *user:* handle removal of `gid_from_name` in Salt develop branch
(https://github.com/saltstack-formulas/vault-formula/commit/dee3748[dee3748^]),
closes
https://github.com/saltstack/salt/issues/48640[saltstack/salt#48640^]

=== Code Refactoring

* *defaults:* place common values in defaults.yaml
(https://github.com/saltstack-formulas/vault-formula/commit/3656e31[3656e31^])

=== Continuous Integration

* *kitchen+travis:* bring into line with `template-formula`
(https://github.com/saltstack-formulas/vault-formula/commit/34f05bd[34f05bd^])

=== Features

* add support for openSUSE
(https://github.com/saltstack-formulas/vault-formula/commit/76b8ac3[76b8ac3^])

=== Tests

* *user+group:* test for vault user/group existence
(https://github.com/saltstack-formulas/vault-formula/commit/ff5cdf9[ff5cdf9^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.5...v1.0.6++[1.0.6^] (2019-06-24)

=== Bug Fixes

* use gpg2
(https://github.com/saltstack-formulas/vault-formula/commit/d755cb4[d755cb4^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.4...v1.0.5++[1.0.5^] (2019-05-15)

=== Documentation

* *readme:* move requirements section under testing header
(https://github.com/saltstack-formulas/vault-formula/commit/dfca3a6[dfca3a6^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.3...v1.0.4++[1.0.4^] (2019-05-14)

=== Continuous Integration

* *kitchen:* don't put Gemfile.lock in git
(https://github.com/saltstack-formulas/vault-formula/commit/cfd5daf[cfd5daf^])
* *kitchen:* update Gemfile from template-formula
(https://github.com/saltstack-formulas/vault-formula/commit/541ec63[541ec63^])
* *travis:* use default bundler on Travis
(https://github.com/saltstack-formulas/vault-formula/commit/b9f40b3[b9f40b3^])

=== Documentation

* *readme:* restore requirements section
(https://github.com/saltstack-formulas/vault-formula/commit/5f2256c[5f2256c^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.2...v1.0.3++[1.0.3^] (2019-05-13)

=== Documentation

* *readme:* improve readme sections
(https://github.com/saltstack-formulas/vault-formula/commit/10e2bde[10e2bde^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2019-05-13)

=== Documentation

* *readme:* update readme, add badges
(https://github.com/saltstack-formulas/vault-formula/commit/1fc3142[1fc3142^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2019-04-20)

=== Code Refactoring

* *kitchen:* prefer `kitchen.yml` to `.kitchen.yml`
(https://github.com/saltstack-formulas/vault-formula/commit/5baaf24[5baaf24^])

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v0.5.1...v1.0.0++[1.0.0^] (2019-04-01)

=== Bug Fixes

* *everything:* review comments & tests
(https://github.com/saltstack-formulas/vault-formula/commit/297d784[297d784^])
* *package:* add missed cleanup & add storage backend to prod test
(https://github.com/saltstack-formulas/vault-formula/commit/d0ed5e5[d0ed5e5^])
* *package:* fix more review comments
(https://github.com/saltstack-formulas/vault-formula/commit/65482c2[65482c2^])
* *service:* re-add support for Ubuntu 14.04 and older
(https://github.com/saltstack-formulas/vault-formula/commit/1b1611f[1b1611f^])
* *upgrade:* upgrade procedure & add MacOS platform
(https://github.com/saltstack-formulas/vault-formula/commit/b7b0d1d[b7b0d1d^])

=== Code Refactoring

* *everything:* overhaul to align with the template-formula
(https://github.com/saltstack-formulas/vault-formula/commit/15d4e34[15d4e34^])
* *map.jinja:* cleanup map.jinja merge & add lookup
(https://github.com/saltstack-formulas/vault-formula/commit/a640f01[a640f01^])
* *service:* move config watch statement as it breaks in dev_mode
(https://github.com/saltstack-formulas/vault-formula/commit/c6ce242[c6ce242^])

=== Features

* *version:* bump version to 1.1.0
(https://github.com/saltstack-formulas/vault-formula/commit/7671f87[7671f87^])

=== Reverts

* *defaults:* some defaults were incorrectly changed
(https://github.com/saltstack-formulas/vault-formula/commit/140db23[140db23^])

=== Tests

* *config:* correct more test cases
(https://github.com/saltstack-formulas/vault-formula/commit/507ee9f[507ee9f^])
* *install_binary:* fix version & hash returned by vault v1.1.0
(https://github.com/saltstack-formulas/vault-formula/commit/8d74960[8d74960^])
* *kitchen:* change version pillar
(https://github.com/saltstack-formulas/vault-formula/commit/7fed7e6[7fed7e6^])
* *manual:* update test, clean link
(https://github.com/saltstack-formulas/vault-formula/commit/1f533d3[1f533d3^])

=== BREAKING CHANGES

* *everything:* This renames all states and the config file being
generated.

== link:++https://github.com/saltstack-formulas/vault-formula/compare/v0.5.0...v0.5.1++[0.5.1^] (2019-03-27)

=== Documentation

* *semantic-release:* implement an automated changelog
(https://github.com/saltstack-formulas/vault-formula/commit/728ebd8[728ebd8^]),
closes
https://github.com/saltstack-formulas/vault-formula/issues/24[#24^]
